% Generated by sql-metadata command in blipkit_sql
:- discontiguous relation/2.
:- discontiguous attribute/3.
:- discontiguous unique/3.

% changes from 47:
% removed regulatory_{factor,feature,feature_object}
%   http://www.ensembl.org/info/docs/api/funcgen/reg_features.html
% moved to schema_ensfungen*.pro

unique(gene_stable_id,gene_id).
unique(gene_stable_id,stable_id).
unique(exon_stable_id,exon_id).
unique(exon_stable_id,stable_id).

unique(gene,gene_id).
unique(gene,display_xref_id).
unique(regulatory_feature,regulatory_feature_id).
unique(regulatory_feature,name).
unique(seq_region,seq_region_id).
unique(seq_region,name).
unique(exon,[seq_region_id,seq_region_start,seq_region_end,seq_region_strand]).
unique(transcript,transcript_id).
unique(transcript_stable_id,transcript_id).
unique(transcript_stable_id,stable_id).
unique(translation,translation_id).
unique(translation_stable_id,translation_id).
unique(translation_stable_id,stable_id).
unique(exon,exon_id).
unique(exon_transcript,[exon_id,transcript_id]). % TODO



%% alt_allele(?ALT_ALLELE_ID:integer, ?GENE_ID:integer) is nondet
% maps to sql table
relation(alt_allele, 2).
attribute(1, alt_allele, alt_allele_id, 'integer unsigned').
attribute(2, alt_allele, gene_id, 'integer unsigned').
%% analysis(?ANALYSIS_ID:smallint, ?CREATED:datetime, ?LOGIC_NAME:string, ?DB:string, ?DB_VERSION:string, ?DB_FILE:string, ?PROGRAM:string, ?PROGRAM_VERSION:string, ?PROGRAM_FILE:string, ?PARAMETERS:string, ?MODULE:string, ?MODULE_VERSION:string, ?GFF_SOURCE:string, ?GFF_FEATURE:string) is nondet
% maps to sql table
relation(analysis, 14).
attribute(1, analysis, analysis_id, smallint).
attribute(2, analysis, created, datetime).
attribute(3, analysis, logic_name, string).
attribute(4, analysis, db, string).
attribute(5, analysis, db_version, string).
attribute(6, analysis, db_file, string).
attribute(7, analysis, program, string).
attribute(8, analysis, program_version, string).
attribute(9, analysis, program_file, string).
attribute(10, analysis, parameters, string).
attribute(11, analysis, module, string).
attribute(12, analysis, module_version, string).
attribute(13, analysis, gff_source, string).
attribute(14, analysis, gff_feature, string).
%% analysis_description(?ANALYSIS_ID:smallint, ?DESCRIPTION:string, ?DISPLAY_LABEL:string, ?DISPLAYABLE:tinyint, ?WEB_DATA:string) is nondet
% maps to sql table
relation(analysis_description, 5).
attribute(1, analysis_description, analysis_id, smallint).
attribute(2, analysis_description, description, string).
attribute(3, analysis_description, display_label, string).
attribute(4, analysis_description, displayable, tinyint).
attribute(5, analysis_description, web_data, string).
%% assembly(?ASM_SEQ_REGION_ID:integer, ?CMP_SEQ_REGION_ID:integer, ?ASM_START:integer, ?ASM_END:integer, ?CMP_START:integer, ?CMP_END:integer, ?ORI:tinyint) is nondet
% maps to sql table
relation(assembly, 7).
attribute(1, assembly, asm_seq_region_id, 'integer unsigned').
attribute(2, assembly, cmp_seq_region_id, 'integer unsigned').
attribute(3, assembly, asm_start, integer).
attribute(4, assembly, asm_end, integer).
attribute(5, assembly, cmp_start, integer).
attribute(6, assembly, cmp_end, integer).
attribute(7, assembly, ori, tinyint).
%% assembly_exception(?ASSEMBLY_EXCEPTION_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?EXC_TYPE:string, ?EXC_SEQ_REGION_ID:integer, ?EXC_SEQ_REGION_START:integer, ?EXC_SEQ_REGION_END:integer, ?ORI:integer) is nondet
% maps to sql table
relation(assembly_exception, 9).
attribute(1, assembly_exception, assembly_exception_id, 'integer unsigned').
attribute(2, assembly_exception, seq_region_id, 'integer unsigned').
attribute(3, assembly_exception, seq_region_start, 'integer unsigned').
attribute(4, assembly_exception, seq_region_end, 'integer unsigned').
attribute(5, assembly_exception, exc_type, string).
attribute(6, assembly_exception, exc_seq_region_id, 'integer unsigned').
attribute(7, assembly_exception, exc_seq_region_start, 'integer unsigned').
attribute(8, assembly_exception, exc_seq_region_end, 'integer unsigned').
attribute(9, assembly_exception, ori, integer).
%% attrib_type(?ATTRIB_TYPE_ID:smallint, ?CODE:string, ?NAME:string, ?DESCRIPTION:string) is nondet
% maps to sql table
relation(attrib_type, 4).
attribute(1, attrib_type, attrib_type_id, smallint).
attribute(2, attrib_type, code, string).
attribute(3, attrib_type, name, string).
attribute(4, attrib_type, description, string).
%% backup_analysis_description(?ANALYSIS_ID:smallint, ?DESCRIPTION:string, ?DISPLAY_LABEL:string, ?DISPLAYABLE:tinyint, ?WEB_DATA:string) is nondet
% maps to sql table
relation(backup_analysis_description, 5).
attribute(1, backup_analysis_description, analysis_id, smallint).
attribute(2, backup_analysis_description, description, string).
attribute(3, backup_analysis_description, display_label, string).
attribute(4, backup_analysis_description, displayable, tinyint).
attribute(5, backup_analysis_description, web_data, string).
%% coord_system(?COORD_SYSTEM_ID:integer, ?SPECIES_ID:integer, ?NAME:string, ?VERSION:string, ?RANK:integer, ?ATTRIB:string) is nondet
% maps to sql table
relation(coord_system, 6).
attribute(1, coord_system, coord_system_id, 'integer unsigned').
attribute(2, coord_system, species_id, 'integer unsigned').
attribute(3, coord_system, name, string).
attribute(4, coord_system, version, string).
attribute(5, coord_system, rank, integer).
attribute(6, coord_system, attrib, string).
%% density_feature(?DENSITY_FEATURE_ID:integer, ?DENSITY_TYPE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?DENSITY_VALUE:float) is nondet
% maps to sql table
relation(density_feature, 6).
attribute(1, density_feature, density_feature_id, 'integer unsigned').
attribute(2, density_feature, density_type_id, 'integer unsigned').
attribute(3, density_feature, seq_region_id, 'integer unsigned').
attribute(4, density_feature, seq_region_start, 'integer unsigned').
attribute(5, density_feature, seq_region_end, 'integer unsigned').
attribute(6, density_feature, density_value, float).
%% density_type(?DENSITY_TYPE_ID:integer, ?ANALYSIS_ID:smallint, ?BLOCK_SIZE:integer, ?REGION_FEATURES:integer, ?VALUE_TYPE:string) is nondet
% maps to sql table
relation(density_type, 5).
attribute(1, density_type, density_type_id, 'integer unsigned').
attribute(2, density_type, analysis_id, smallint).
attribute(3, density_type, block_size, integer).
attribute(4, density_type, region_features, integer).
attribute(5, density_type, value_type, string).
%% ditag(?DITAG_ID:integer, ?NAME:string, ?TYPE:string, ?TAG_COUNT:smallint, ?SEQUENCE:string) is nondet
% maps to sql table
relation(ditag, 5).
attribute(1, ditag, ditag_id, 'integer unsigned').
attribute(2, ditag, name, string).
attribute(3, ditag, type, string).
attribute(4, ditag, tag_count, smallint).
attribute(5, ditag, sequence, string).
%% ditag_feature(?DITAG_FEATURE_ID:integer, ?DITAG_ID:integer, ?DITAG_PAIR_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?ANALYSIS_ID:smallint, ?HIT_START:integer, ?HIT_END:integer, ?HIT_STRAND:tinyint, ?CIGAR_LINE:string, ?DITAG_SIDE:string) is nondet
% maps to sql table
relation(ditag_feature, 13).
attribute(1, ditag_feature, ditag_feature_id, 'integer unsigned').
attribute(2, ditag_feature, ditag_id, 'integer unsigned').
attribute(3, ditag_feature, ditag_pair_id, 'integer unsigned').
attribute(4, ditag_feature, seq_region_id, 'integer unsigned').
attribute(5, ditag_feature, seq_region_start, 'integer unsigned').
attribute(6, ditag_feature, seq_region_end, 'integer unsigned').
attribute(7, ditag_feature, seq_region_strand, tinyint).
attribute(8, ditag_feature, analysis_id, smallint).
attribute(9, ditag_feature, hit_start, 'integer unsigned').
attribute(10, ditag_feature, hit_end, 'integer unsigned').
attribute(11, ditag_feature, hit_strand, tinyint).
attribute(12, ditag_feature, cigar_line, string).
attribute(13, ditag_feature, ditag_side, string).
%% dna(?SEQ_REGION_ID:integer, ?SEQUENCE:string) is nondet
% maps to sql table
relation(dna, 2).
attribute(1, dna, seq_region_id, 'integer unsigned').
attribute(2, dna, sequence, string).
%% dna_align_feature(?DNA_ALIGN_FEATURE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?HIT_START:integer, ?HIT_END:integer, ?HIT_STRAND:tinyint, ?HIT_NAME:string, ?ANALYSIS_ID:smallint, ?SCORE:double, ?EVALUE:double, ?PERC_IDENT:float, ?CIGAR_LINE:string, ?EXTERNAL_DB_ID:smallint, ?HCOVERAGE:double, ?EXTERNAL_DATA:string) is nondet
% maps to sql table
relation(dna_align_feature, 17).
attribute(1, dna_align_feature, dna_align_feature_id, 'integer unsigned').
attribute(2, dna_align_feature, seq_region_id, 'integer unsigned').
attribute(3, dna_align_feature, seq_region_start, 'integer unsigned').
attribute(4, dna_align_feature, seq_region_end, 'integer unsigned').
attribute(5, dna_align_feature, seq_region_strand, tinyint).
attribute(6, dna_align_feature, hit_start, integer).
attribute(7, dna_align_feature, hit_end, integer).
attribute(8, dna_align_feature, hit_strand, tinyint).
attribute(9, dna_align_feature, hit_name, string).
attribute(10, dna_align_feature, analysis_id, smallint).
attribute(11, dna_align_feature, score, double).
attribute(12, dna_align_feature, evalue, double).
attribute(13, dna_align_feature, perc_ident, float).
attribute(14, dna_align_feature, cigar_line, string).
attribute(15, dna_align_feature, external_db_id, smallint).
attribute(16, dna_align_feature, hcoverage, double).
attribute(17, dna_align_feature, external_data, string).
%% dnac(?SEQ_REGION_ID:integer, ?SEQUENCE:blob, ?N_LINE:string) is nondet
% maps to sql table
relation(dnac, 3).
attribute(1, dnac, seq_region_id, 'integer unsigned').
attribute(2, dnac, sequence, blob).
attribute(3, dnac, n_line, string).
%% exon(?EXON_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?PHASE:tinyint, ?END_PHASE:tinyint, ?IS_CURRENT:tinyint) is nondet
% maps to sql table
relation(exon, 8).
attribute(1, exon, exon_id, 'integer unsigned').
attribute(2, exon, seq_region_id, 'integer unsigned').
attribute(3, exon, seq_region_start, 'integer unsigned').
attribute(4, exon, seq_region_end, 'integer unsigned').
attribute(5, exon, seq_region_strand, tinyint).
attribute(6, exon, phase, tinyint).
attribute(7, exon, end_phase, tinyint).
attribute(8, exon, is_current, tinyint).
%% exon_stable_id(?EXON_ID:integer, ?STABLE_ID:string, ?VERSION:integer, ?CREATED_DATE:datetime, ?MODIFIED_DATE:datetime) is nondet
% maps to sql table
relation(exon_stable_id, 5).
attribute(1, exon_stable_id, exon_id, 'integer unsigned').
attribute(2, exon_stable_id, stable_id, string).
attribute(3, exon_stable_id, version, integer).
attribute(4, exon_stable_id, created_date, datetime).
attribute(5, exon_stable_id, modified_date, datetime).
%% exon_transcript(?EXON_ID:integer, ?TRANSCRIPT_ID:integer, ?RANK:integer) is nondet
% maps to sql table
relation(exon_transcript, 3).
attribute(1, exon_transcript, exon_id, 'integer unsigned').
attribute(2, exon_transcript, transcript_id, 'integer unsigned').
attribute(3, exon_transcript, rank, integer).
%% external_db(?EXTERNAL_DB_ID:smallint, ?DB_NAME:string, ?DB_RELEASE:string, ?STATUS:string, ?DBPRIMARY_ACC_LINKABLE:tinyint, ?DISPLAY_LABEL_LINKABLE:tinyint, ?PRIORITY:integer, ?DB_DISPLAY_NAME:string, ?TYPE:string, ?SECONDARY_DB_NAME:string, ?SECONDARY_DB_TABLE:string) is nondet
% maps to sql table
relation(external_db, 11).
attribute(1, external_db, external_db_id, smallint).
attribute(2, external_db, db_name, string).
attribute(3, external_db, db_release, string).
attribute(4, external_db, status, string).
attribute(5, external_db, dbprimary_acc_linkable, tinyint).
attribute(6, external_db, display_label_linkable, tinyint).
attribute(7, external_db, priority, integer).
attribute(8, external_db, db_display_name, string).
attribute(9, external_db, type, string).
attribute(10, external_db, secondary_db_name, string).
attribute(11, external_db, secondary_db_table, string).
%% external_synonym(?XREF_ID:integer, ?SYNONYM:string) is nondet
% maps to sql table
relation(external_synonym, 2).
attribute(1, external_synonym, xref_id, 'integer unsigned').
attribute(2, external_synonym, synonym, string).
%% gene(?GENE_ID:integer, ?BIOTYPE:string, ?ANALYSIS_ID:smallint, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?DISPLAY_XREF_ID:integer, ?SOURCE:string, ?STATUS:string, ?DESCRIPTION:string, ?IS_CURRENT:tinyint, ?CANONICAL_TRANSCRIPT_ID:integer, ?CANONICAL_ANNOTATION:string) is nondet
% maps to sql table
relation(gene, 14).
attribute(1, gene, gene_id, 'integer unsigned').
attribute(2, gene, biotype, string).
attribute(3, gene, analysis_id, smallint).
attribute(4, gene, seq_region_id, 'integer unsigned').
attribute(5, gene, seq_region_start, 'integer unsigned').
attribute(6, gene, seq_region_end, 'integer unsigned').
attribute(7, gene, seq_region_strand, tinyint).
attribute(8, gene, display_xref_id, 'integer unsigned').
attribute(9, gene, source, string).
attribute(10, gene, status, string).
attribute(11, gene, description, string).
attribute(12, gene, is_current, tinyint).
attribute(13, gene, canonical_transcript_id, 'integer unsigned').
attribute(14, gene, canonical_annotation, string).
%% gene_archive(?GENE_STABLE_ID:string, ?GENE_VERSION:smallint, ?TRANSCRIPT_STABLE_ID:string, ?TRANSCRIPT_VERSION:smallint, ?TRANSLATION_STABLE_ID:string, ?TRANSLATION_VERSION:smallint, ?PEPTIDE_ARCHIVE_ID:integer, ?MAPPING_SESSION_ID:integer) is nondet
% maps to sql table
relation(gene_archive, 8).
attribute(1, gene_archive, gene_stable_id, string).
attribute(2, gene_archive, gene_version, smallint).
attribute(3, gene_archive, transcript_stable_id, string).
attribute(4, gene_archive, transcript_version, smallint).
attribute(5, gene_archive, translation_stable_id, string).
attribute(6, gene_archive, translation_version, smallint).
attribute(7, gene_archive, peptide_archive_id, 'integer unsigned').
attribute(8, gene_archive, mapping_session_id, 'integer unsigned').
%% gene_attrib(?GENE_ID:integer, ?ATTRIB_TYPE_ID:smallint, ?VALUE:string) is nondet
% maps to sql table
relation(gene_attrib, 3).
attribute(1, gene_attrib, gene_id, 'integer unsigned').
attribute(2, gene_attrib, attrib_type_id, smallint).
attribute(3, gene_attrib, value, string).
%% gene_stable_id(?GENE_ID:integer, ?STABLE_ID:string, ?VERSION:integer, ?CREATED_DATE:datetime, ?MODIFIED_DATE:datetime) is nondet
% maps to sql table
relation(gene_stable_id, 5).
attribute(1, gene_stable_id, gene_id, 'integer unsigned').
attribute(2, gene_stable_id, stable_id, string).
attribute(3, gene_stable_id, version, integer).
attribute(4, gene_stable_id, created_date, datetime).
attribute(5, gene_stable_id, modified_date, datetime).
%% go_xref(?OBJECT_XREF_ID:integer, ?LINKAGE_TYPE:string, ?SOURCE_XREF_ID:integer) is nondet
% maps to sql table
relation(go_xref, 3).
attribute(1, go_xref, object_xref_id, 'integer unsigned').
attribute(2, go_xref, linkage_type, string).
attribute(3, go_xref, source_xref_id, 'integer unsigned').
%% identity_xref(?OBJECT_XREF_ID:integer, ?QUERY_IDENTITY:integer, ?TARGET_IDENTITY:integer, ?HIT_START:integer, ?HIT_END:integer, ?TRANSLATION_START:integer, ?TRANSLATION_END:integer, ?CIGAR_LINE:string, ?SCORE:double, ?EVALUE:double, ?ANALYSIS_ID:smallint) is nondet
% maps to sql table
relation(identity_xref, 11).
attribute(1, identity_xref, object_xref_id, 'integer unsigned').
attribute(2, identity_xref, query_identity, integer).
attribute(3, identity_xref, target_identity, integer).
attribute(4, identity_xref, hit_start, integer).
attribute(5, identity_xref, hit_end, integer).
attribute(6, identity_xref, translation_start, integer).
attribute(7, identity_xref, translation_end, integer).
attribute(8, identity_xref, cigar_line, string).
attribute(9, identity_xref, score, double).
attribute(10, identity_xref, evalue, double).
attribute(11, identity_xref, analysis_id, smallint).
%% interpro(?INTERPRO_AC:string, ?ID:string) is nondet
% maps to sql table
relation(interpro, 2).
attribute(1, interpro, interpro_ac, string).
attribute(2, interpro, id, string).
%% karyotype(?KARYOTYPE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?BAND:string, ?STAIN:string) is nondet
% maps to sql table
relation(karyotype, 6).
attribute(1, karyotype, karyotype_id, 'integer unsigned').
attribute(2, karyotype, seq_region_id, 'integer unsigned').
attribute(3, karyotype, seq_region_start, integer).
attribute(4, karyotype, seq_region_end, integer).
attribute(5, karyotype, band, string).
attribute(6, karyotype, stain, string).
%% map(?MAP_ID:integer, ?MAP_NAME:string) is nondet
% maps to sql table
relation(map, 2).
attribute(1, map, map_id, 'integer unsigned').
attribute(2, map, map_name, string).
%% mapping_session(?MAPPING_SESSION_ID:integer, ?OLD_DB_NAME:string, ?NEW_DB_NAME:string, ?OLD_RELEASE:string, ?NEW_RELEASE:string, ?OLD_ASSEMBLY:string, ?NEW_ASSEMBLY:string, ?CREATED:datetime) is nondet
% maps to sql table
relation(mapping_session, 8).
attribute(1, mapping_session, mapping_session_id, 'integer unsigned').
attribute(2, mapping_session, old_db_name, string).
attribute(3, mapping_session, new_db_name, string).
attribute(4, mapping_session, old_release, string).
attribute(5, mapping_session, new_release, string).
attribute(6, mapping_session, old_assembly, string).
attribute(7, mapping_session, new_assembly, string).
attribute(8, mapping_session, created, datetime).
%% mapping_set(?MAPPING_SET_ID:integer, ?SCHEMA_BUILD:string) is nondet
% maps to sql table
relation(mapping_set, 2).
attribute(1, mapping_set, mapping_set_id, 'integer unsigned').
attribute(2, mapping_set, schema_build, string).
%% marker(?MARKER_ID:integer, ?DISPLAY_MARKER_SYNONYM_ID:integer, ?LEFT_PRIMER:string, ?RIGHT_PRIMER:string, ?MIN_PRIMER_DIST:integer, ?MAX_PRIMER_DIST:integer, ?PRIORITY:integer, ?TYPE:string) is nondet
% maps to sql table
relation(marker, 8).
attribute(1, marker, marker_id, 'integer unsigned').
attribute(2, marker, display_marker_synonym_id, 'integer unsigned').
attribute(3, marker, left_primer, string).
attribute(4, marker, right_primer, string).
attribute(5, marker, min_primer_dist, 'integer unsigned').
attribute(6, marker, max_primer_dist, 'integer unsigned').
attribute(7, marker, priority, integer).
attribute(8, marker, type, string).
%% marker_feature(?MARKER_FEATURE_ID:integer, ?MARKER_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?ANALYSIS_ID:smallint, ?MAP_WEIGHT:integer) is nondet
% maps to sql table
relation(marker_feature, 7).
attribute(1, marker_feature, marker_feature_id, 'integer unsigned').
attribute(2, marker_feature, marker_id, 'integer unsigned').
attribute(3, marker_feature, seq_region_id, 'integer unsigned').
attribute(4, marker_feature, seq_region_start, 'integer unsigned').
attribute(5, marker_feature, seq_region_end, 'integer unsigned').
attribute(6, marker_feature, analysis_id, smallint).
attribute(7, marker_feature, map_weight, 'integer unsigned').
%% marker_map_location(?MARKER_ID:integer, ?MAP_ID:integer, ?CHROMOSOME_NAME:string, ?MARKER_SYNONYM_ID:integer, ?POSITION:string, ?LOD_SCORE:double) is nondet
% maps to sql table
relation(marker_map_location, 6).
attribute(1, marker_map_location, marker_id, 'integer unsigned').
attribute(2, marker_map_location, map_id, 'integer unsigned').
attribute(3, marker_map_location, chromosome_name, string).
attribute(4, marker_map_location, marker_synonym_id, 'integer unsigned').
attribute(5, marker_map_location, position, string).
attribute(6, marker_map_location, lod_score, double).
%% marker_synonym(?MARKER_SYNONYM_ID:integer, ?MARKER_ID:integer, ?SOURCE:string, ?NAME:string) is nondet
% maps to sql table
relation(marker_synonym, 4).
attribute(1, marker_synonym, marker_synonym_id, 'integer unsigned').
attribute(2, marker_synonym, marker_id, 'integer unsigned').
attribute(3, marker_synonym, source, string).
attribute(4, marker_synonym, name, string).
%% meta(?META_ID:integer, ?SPECIES_ID:integer, ?META_KEY:string, ?META_VALUE:string) is nondet
% maps to sql table
relation(meta, 4).
attribute(1, meta, meta_id, integer).
attribute(2, meta, species_id, 'integer unsigned').
attribute(3, meta, meta_key, string).
attribute(4, meta, meta_value, string).
%% meta_coord(?TABLE_NAME:string, ?COORD_SYSTEM_ID:integer, ?MAX_LENGTH:integer) is nondet
% maps to sql table
relation(meta_coord, 3).
attribute(1, meta_coord, table_name, string).
attribute(2, meta_coord, coord_system_id, 'integer unsigned').
attribute(3, meta_coord, max_length, integer).
%% misc_attrib(?MISC_FEATURE_ID:integer, ?ATTRIB_TYPE_ID:smallint, ?VALUE:string) is nondet
% maps to sql table
relation(misc_attrib, 3).
attribute(1, misc_attrib, misc_feature_id, 'integer unsigned').
attribute(2, misc_attrib, attrib_type_id, smallint).
attribute(3, misc_attrib, value, string).
%% misc_feature(?MISC_FEATURE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint) is nondet
% maps to sql table
relation(misc_feature, 5).
attribute(1, misc_feature, misc_feature_id, 'integer unsigned').
attribute(2, misc_feature, seq_region_id, 'integer unsigned').
attribute(3, misc_feature, seq_region_start, 'integer unsigned').
attribute(4, misc_feature, seq_region_end, 'integer unsigned').
attribute(5, misc_feature, seq_region_strand, tinyint).
%% misc_feature_misc_set(?MISC_FEATURE_ID:integer, ?MISC_SET_ID:smallint) is nondet
% maps to sql table
relation(misc_feature_misc_set, 2).
attribute(1, misc_feature_misc_set, misc_feature_id, 'integer unsigned').
attribute(2, misc_feature_misc_set, misc_set_id, smallint).
%% misc_set(?MISC_SET_ID:smallint, ?CODE:string, ?NAME:string, ?DESCRIPTION:string, ?MAX_LENGTH:integer) is nondet
% maps to sql table
relation(misc_set, 5).
attribute(1, misc_set, misc_set_id, smallint).
attribute(2, misc_set, code, string).
attribute(3, misc_set, name, string).
attribute(4, misc_set, description, string).
attribute(5, misc_set, max_length, 'integer unsigned').
%% object_xref(?OBJECT_XREF_ID:integer, ?ENSEMBL_ID:integer, ?ENSEMBL_OBJECT_TYPE:string, ?XREF_ID:integer, ?LINKAGE_ANNOTATION:string) is nondet
% maps to sql table
relation(object_xref, 5).
attribute(1, object_xref, object_xref_id, 'integer unsigned').
attribute(2, object_xref, ensembl_id, 'integer unsigned').
attribute(3, object_xref, ensembl_object_type, string).
attribute(4, object_xref, xref_id, 'integer unsigned').
attribute(5, object_xref, linkage_annotation, string).
%% oligo_array(?OLIGO_ARRAY_ID:integer, ?PARENT_ARRAY_ID:integer, ?PROBE_SETSIZE:tinyint, ?NAME:string, ?TYPE:string) is nondet
% maps to sql table
relation(oligo_array, 5).
attribute(1, oligo_array, oligo_array_id, 'integer unsigned').
attribute(2, oligo_array, parent_array_id, 'integer unsigned').
attribute(3, oligo_array, probe_setsize, tinyint).
attribute(4, oligo_array, name, string).
attribute(5, oligo_array, type, string).
%% oligo_feature(?OLIGO_FEATURE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?MISMATCHES:tinyint, ?OLIGO_PROBE_ID:integer, ?ANALYSIS_ID:smallint) is nondet
% maps to sql table
relation(oligo_feature, 8).
attribute(1, oligo_feature, oligo_feature_id, 'integer unsigned').
attribute(2, oligo_feature, seq_region_id, 'integer unsigned').
attribute(3, oligo_feature, seq_region_start, 'integer unsigned').
attribute(4, oligo_feature, seq_region_end, 'integer unsigned').
attribute(5, oligo_feature, seq_region_strand, tinyint).
attribute(6, oligo_feature, mismatches, tinyint).
attribute(7, oligo_feature, oligo_probe_id, 'integer unsigned').
attribute(8, oligo_feature, analysis_id, smallint).
%% oligo_probe(?OLIGO_PROBE_ID:integer, ?OLIGO_ARRAY_ID:integer, ?PROBESET:string, ?NAME:string, ?DESCRIPTION:string, ?LENGTH:smallint) is nondet
% maps to sql table
relation(oligo_probe, 6).
attribute(1, oligo_probe, oligo_probe_id, 'integer unsigned').
attribute(2, oligo_probe, oligo_array_id, 'integer unsigned').
attribute(3, oligo_probe, probeset, string).
attribute(4, oligo_probe, name, string).
attribute(5, oligo_probe, description, string).
attribute(6, oligo_probe, length, smallint).
%% peptide_archive(?PEPTIDE_ARCHIVE_ID:integer, ?MD5_CHECKSUM:string, ?PEPTIDE_SEQ:string) is nondet
% maps to sql table
relation(peptide_archive, 3).
attribute(1, peptide_archive, peptide_archive_id, 'integer unsigned').
attribute(2, peptide_archive, md5_checksum, string).
attribute(3, peptide_archive, peptide_seq, string).
%% prediction_exon(?PREDICTION_EXON_ID:integer, ?PREDICTION_TRANSCRIPT_ID:integer, ?EXON_RANK:smallint, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?START_PHASE:tinyint, ?SCORE:double, ?P_VALUE:double) is nondet
% maps to sql table
relation(prediction_exon, 10).
attribute(1, prediction_exon, prediction_exon_id, 'integer unsigned').
attribute(2, prediction_exon, prediction_transcript_id, 'integer unsigned').
attribute(3, prediction_exon, exon_rank, smallint).
attribute(4, prediction_exon, seq_region_id, 'integer unsigned').
attribute(5, prediction_exon, seq_region_start, 'integer unsigned').
attribute(6, prediction_exon, seq_region_end, 'integer unsigned').
attribute(7, prediction_exon, seq_region_strand, tinyint).
attribute(8, prediction_exon, start_phase, tinyint).
attribute(9, prediction_exon, score, double).
attribute(10, prediction_exon, p_value, double).
%% prediction_transcript(?PREDICTION_TRANSCRIPT_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?ANALYSIS_ID:smallint, ?DISPLAY_LABEL:string) is nondet
% maps to sql table
relation(prediction_transcript, 7).
attribute(1, prediction_transcript, prediction_transcript_id, 'integer unsigned').
attribute(2, prediction_transcript, seq_region_id, 'integer unsigned').
attribute(3, prediction_transcript, seq_region_start, 'integer unsigned').
attribute(4, prediction_transcript, seq_region_end, 'integer unsigned').
attribute(5, prediction_transcript, seq_region_strand, tinyint).
attribute(6, prediction_transcript, analysis_id, smallint).
attribute(7, prediction_transcript, display_label, string).
%% protein_align_feature(?PROTEIN_ALIGN_FEATURE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?HIT_START:integer, ?HIT_END:integer, ?HIT_NAME:string, ?ANALYSIS_ID:smallint, ?SCORE:double, ?EVALUE:double, ?PERC_IDENT:float, ?CIGAR_LINE:string, ?EXTERNAL_DB_ID:smallint, ?HCOVERAGE:double) is nondet
% maps to sql table
relation(protein_align_feature, 15).
attribute(1, protein_align_feature, protein_align_feature_id, 'integer unsigned').
attribute(2, protein_align_feature, seq_region_id, 'integer unsigned').
attribute(3, protein_align_feature, seq_region_start, 'integer unsigned').
attribute(4, protein_align_feature, seq_region_end, 'integer unsigned').
attribute(5, protein_align_feature, seq_region_strand, tinyint).
attribute(6, protein_align_feature, hit_start, integer).
attribute(7, protein_align_feature, hit_end, integer).
attribute(8, protein_align_feature, hit_name, string).
attribute(9, protein_align_feature, analysis_id, smallint).
attribute(10, protein_align_feature, score, double).
attribute(11, protein_align_feature, evalue, double).
attribute(12, protein_align_feature, perc_ident, float).
attribute(13, protein_align_feature, cigar_line, string).
attribute(14, protein_align_feature, external_db_id, smallint).
attribute(15, protein_align_feature, hcoverage, double).
%% protein_feature(?PROTEIN_FEATURE_ID:integer, ?TRANSLATION_ID:integer, ?SEQ_START:integer, ?SEQ_END:integer, ?HIT_START:integer, ?HIT_END:integer, ?HIT_NAME:string, ?ANALYSIS_ID:smallint, ?SCORE:double, ?EVALUE:double, ?PERC_IDENT:float, ?EXTERNAL_DATA:string) is nondet
% maps to sql table
relation(protein_feature, 12).
attribute(1, protein_feature, protein_feature_id, 'integer unsigned').
attribute(2, protein_feature, translation_id, 'integer unsigned').
attribute(3, protein_feature, seq_start, integer).
attribute(4, protein_feature, seq_end, integer).
attribute(5, protein_feature, hit_start, integer).
attribute(6, protein_feature, hit_end, integer).
attribute(7, protein_feature, hit_name, string).
attribute(8, protein_feature, analysis_id, smallint).
attribute(9, protein_feature, score, double).
attribute(10, protein_feature, evalue, double).
attribute(11, protein_feature, perc_ident, float).
attribute(12, protein_feature, external_data, string).
%% qtl(?QTL_ID:integer, ?TRAIT:string, ?LOD_SCORE:float, ?FLANK_MARKER_ID_1:integer, ?FLANK_MARKER_ID_2:integer, ?PEAK_MARKER_ID:integer) is nondet
% maps to sql table
relation(qtl, 6).
attribute(1, qtl, qtl_id, 'integer unsigned').
attribute(2, qtl, trait, string).
attribute(3, qtl, lod_score, float).
attribute(4, qtl, flank_marker_id_1, 'integer unsigned').
attribute(5, qtl, flank_marker_id_2, 'integer unsigned').
attribute(6, qtl, peak_marker_id, 'integer unsigned').
%% qtl_feature(?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?QTL_ID:integer, ?ANALYSIS_ID:smallint) is nondet
% maps to sql table
relation(qtl_feature, 5).
attribute(1, qtl_feature, seq_region_id, 'integer unsigned').
attribute(2, qtl_feature, seq_region_start, 'integer unsigned').
attribute(3, qtl_feature, seq_region_end, 'integer unsigned').
attribute(4, qtl_feature, qtl_id, 'integer unsigned').
attribute(5, qtl_feature, analysis_id, smallint).
%% qtl_synonym(?QTL_SYNONYM_ID:integer, ?QTL_ID:integer, ?SOURCE_DATABASE:string, ?SOURCE_PRIMARY_ID:string) is nondet
% maps to sql table
relation(qtl_synonym, 4).
attribute(1, qtl_synonym, qtl_synonym_id, 'integer unsigned').
attribute(2, qtl_synonym, qtl_id, 'integer unsigned').
attribute(3, qtl_synonym, source_database, string).
attribute(4, qtl_synonym, source_primary_id, string).
%% repeat_consensus(?REPEAT_CONSENSUS_ID:integer, ?REPEAT_NAME:string, ?REPEAT_CLASS:string, ?REPEAT_TYPE:string, ?REPEAT_CONSENSUS:string) is nondet
% maps to sql table
relation(repeat_consensus, 5).
attribute(1, repeat_consensus, repeat_consensus_id, 'integer unsigned').
attribute(2, repeat_consensus, repeat_name, string).
attribute(3, repeat_consensus, repeat_class, string).
attribute(4, repeat_consensus, repeat_type, string).
attribute(5, repeat_consensus, repeat_consensus, string).
%% repeat_feature(?REPEAT_FEATURE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?REPEAT_START:integer, ?REPEAT_END:integer, ?REPEAT_CONSENSUS_ID:integer, ?ANALYSIS_ID:smallint, ?SCORE:double) is nondet
% maps to sql table
relation(repeat_feature, 10).
attribute(1, repeat_feature, repeat_feature_id, 'integer unsigned').
attribute(2, repeat_feature, seq_region_id, 'integer unsigned').
attribute(3, repeat_feature, seq_region_start, 'integer unsigned').
attribute(4, repeat_feature, seq_region_end, 'integer unsigned').
attribute(5, repeat_feature, seq_region_strand, tinyint).
attribute(6, repeat_feature, repeat_start, integer).
attribute(7, repeat_feature, repeat_end, integer).
attribute(8, repeat_feature, repeat_consensus_id, 'integer unsigned').
attribute(9, repeat_feature, analysis_id, smallint).
attribute(10, repeat_feature, score, double).
%% seq_region(?SEQ_REGION_ID:integer, ?NAME:string, ?COORD_SYSTEM_ID:integer, ?LENGTH:integer) is nondet
% maps to sql table
relation(seq_region, 4).
attribute(1, seq_region, seq_region_id, 'integer unsigned').
attribute(2, seq_region, name, string).
attribute(3, seq_region, coord_system_id, 'integer unsigned').
attribute(4, seq_region, length, integer).
%% seq_region_attrib(?SEQ_REGION_ID:integer, ?ATTRIB_TYPE_ID:smallint, ?VALUE:string) is nondet
% maps to sql table
relation(seq_region_attrib, 3).
attribute(1, seq_region_attrib, seq_region_id, 'integer unsigned').
attribute(2, seq_region_attrib, attrib_type_id, smallint).
attribute(3, seq_region_attrib, value, string).
%% seq_region_mapping(?EXTERNAL_SEQ_REGION_ID:integer, ?INTERNAL_SEQ_REGION_ID:integer, ?MAPPING_SET_ID:integer) is nondet
% maps to sql table
relation(seq_region_mapping, 3).
attribute(1, seq_region_mapping, external_seq_region_id, 'integer unsigned').
attribute(2, seq_region_mapping, internal_seq_region_id, 'integer unsigned').
attribute(3, seq_region_mapping, mapping_set_id, 'integer unsigned').
%% simple_feature(?SIMPLE_FEATURE_ID:integer, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?DISPLAY_LABEL:string, ?ANALYSIS_ID:smallint, ?SCORE:double) is nondet
% maps to sql table
relation(simple_feature, 8).
attribute(1, simple_feature, simple_feature_id, 'integer unsigned').
attribute(2, simple_feature, seq_region_id, 'integer unsigned').
attribute(3, simple_feature, seq_region_start, 'integer unsigned').
attribute(4, simple_feature, seq_region_end, 'integer unsigned').
attribute(5, simple_feature, seq_region_strand, tinyint).
attribute(6, simple_feature, display_label, string).
attribute(7, simple_feature, analysis_id, smallint).
attribute(8, simple_feature, score, double).
%% stable_id_event(?OLD_STABLE_ID:string, ?OLD_VERSION:smallint, ?NEW_STABLE_ID:string, ?NEW_VERSION:smallint, ?MAPPING_SESSION_ID:integer, ?TYPE:string, ?SCORE:float) is nondet
% maps to sql table
relation(stable_id_event, 7).
attribute(1, stable_id_event, old_stable_id, string).
attribute(2, stable_id_event, old_version, smallint).
attribute(3, stable_id_event, new_stable_id, string).
attribute(4, stable_id_event, new_version, smallint).
attribute(5, stable_id_event, mapping_session_id, 'integer unsigned').
attribute(6, stable_id_event, type, string).
attribute(7, stable_id_event, score, float).
%% supporting_feature(?EXON_ID:integer, ?FEATURE_TYPE:string, ?FEATURE_ID:integer) is nondet
% maps to sql table
relation(supporting_feature, 3).
attribute(1, supporting_feature, exon_id, 'integer unsigned').
attribute(2, supporting_feature, feature_type, string).
attribute(3, supporting_feature, feature_id, 'integer unsigned').
%% transcript(?TRANSCRIPT_ID:integer, ?GENE_ID:integer, ?ANALYSIS_ID:smallint, ?SEQ_REGION_ID:integer, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?DISPLAY_XREF_ID:integer, ?BIOTYPE:string, ?STATUS:string, ?DESCRIPTION:string, ?IS_CURRENT:tinyint) is nondet
% maps to sql table
relation(transcript, 12).
attribute(1, transcript, transcript_id, 'integer unsigned').
attribute(2, transcript, gene_id, 'integer unsigned').
attribute(3, transcript, analysis_id, smallint).
attribute(4, transcript, seq_region_id, 'integer unsigned').
attribute(5, transcript, seq_region_start, 'integer unsigned').
attribute(6, transcript, seq_region_end, 'integer unsigned').
attribute(7, transcript, seq_region_strand, tinyint).
attribute(8, transcript, display_xref_id, 'integer unsigned').
attribute(9, transcript, biotype, string).
attribute(10, transcript, status, string).
attribute(11, transcript, description, string).
attribute(12, transcript, is_current, tinyint).
%% transcript_attrib(?TRANSCRIPT_ID:integer, ?ATTRIB_TYPE_ID:smallint, ?VALUE:string) is nondet
% maps to sql table
relation(transcript_attrib, 3).
attribute(1, transcript_attrib, transcript_id, 'integer unsigned').
attribute(2, transcript_attrib, attrib_type_id, smallint).
attribute(3, transcript_attrib, value, string).
%% transcript_stable_id(?TRANSCRIPT_ID:integer, ?STABLE_ID:string, ?VERSION:integer, ?CREATED_DATE:datetime, ?MODIFIED_DATE:datetime) is nondet
% maps to sql table
relation(transcript_stable_id, 5).
attribute(1, transcript_stable_id, transcript_id, 'integer unsigned').
attribute(2, transcript_stable_id, stable_id, string).
attribute(3, transcript_stable_id, version, integer).
attribute(4, transcript_stable_id, created_date, datetime).
attribute(5, transcript_stable_id, modified_date, datetime).
%% transcript_supporting_feature(?TRANSCRIPT_ID:integer, ?FEATURE_TYPE:string, ?FEATURE_ID:integer) is nondet
% maps to sql table
relation(transcript_supporting_feature, 3).
attribute(1, transcript_supporting_feature, transcript_id, 'integer unsigned').
attribute(2, transcript_supporting_feature, feature_type, string).
attribute(3, transcript_supporting_feature, feature_id, 'integer unsigned').
%% translation(?TRANSLATION_ID:integer, ?TRANSCRIPT_ID:integer, ?SEQ_START:integer, ?START_EXON_ID:integer, ?SEQ_END:integer, ?END_EXON_ID:integer) is nondet
% maps to sql table
relation(translation, 6).
attribute(1, translation, translation_id, 'integer unsigned').
attribute(2, translation, transcript_id, 'integer unsigned').
attribute(3, translation, seq_start, integer).
attribute(4, translation, start_exon_id, 'integer unsigned').
attribute(5, translation, seq_end, integer).
attribute(6, translation, end_exon_id, 'integer unsigned').
%% translation_attrib(?TRANSLATION_ID:integer, ?ATTRIB_TYPE_ID:smallint, ?VALUE:string) is nondet
% maps to sql table
relation(translation_attrib, 3).
attribute(1, translation_attrib, translation_id, 'integer unsigned').
attribute(2, translation_attrib, attrib_type_id, smallint).
attribute(3, translation_attrib, value, string).
%% translation_stable_id(?TRANSLATION_ID:integer, ?STABLE_ID:string, ?VERSION:integer, ?CREATED_DATE:datetime, ?MODIFIED_DATE:datetime) is nondet
% maps to sql table
relation(translation_stable_id, 5).
attribute(1, translation_stable_id, translation_id, 'integer unsigned').
attribute(2, translation_stable_id, stable_id, string).
attribute(3, translation_stable_id, version, integer).
attribute(4, translation_stable_id, created_date, datetime).
attribute(5, translation_stable_id, modified_date, datetime).
%% unconventional_transcript_association(?TRANSCRIPT_ID:integer, ?GENE_ID:integer, ?INTERACTION_TYPE:string) is nondet
% maps to sql table
relation(unconventional_transcript_association, 3).
attribute(1, unconventional_transcript_association, transcript_id, 'integer unsigned').
attribute(2, unconventional_transcript_association, gene_id, 'integer unsigned').
attribute(3, unconventional_transcript_association, interaction_type, string).
%% unmapped_object(?UNMAPPED_OBJECT_ID:integer, ?TYPE:string, ?ANALYSIS_ID:smallint, ?EXTERNAL_DB_ID:smallint, ?IDENTIFIER:string, ?UNMAPPED_REASON_ID:smallint, ?QUERY_SCORE:double, ?TARGET_SCORE:double, ?ENSEMBL_ID:integer, ?ENSEMBL_OBJECT_TYPE:string, ?PARENT:string) is nondet
% maps to sql table
relation(unmapped_object, 11).
attribute(1, unmapped_object, unmapped_object_id, 'integer unsigned').
attribute(2, unmapped_object, type, string).
attribute(3, unmapped_object, analysis_id, smallint).
attribute(4, unmapped_object, external_db_id, smallint).
attribute(5, unmapped_object, identifier, string).
attribute(6, unmapped_object, unmapped_reason_id, smallint).
attribute(7, unmapped_object, query_score, double).
attribute(8, unmapped_object, target_score, double).
attribute(9, unmapped_object, ensembl_id, 'integer unsigned').
attribute(10, unmapped_object, ensembl_object_type, string).
attribute(11, unmapped_object, parent, string).
%% unmapped_reason(?UNMAPPED_REASON_ID:smallint, ?SUMMARY_DESCRIPTION:string, ?FULL_DESCRIPTION:string) is nondet
% maps to sql table
relation(unmapped_reason, 3).
attribute(1, unmapped_reason, unmapped_reason_id, smallint).
attribute(2, unmapped_reason, summary_description, string).
attribute(3, unmapped_reason, full_description, string).
%% xref(?XREF_ID:integer, ?EXTERNAL_DB_ID:smallint, ?DBPRIMARY_ACC:string, ?DISPLAY_LABEL:string, ?VERSION:string, ?DESCRIPTION:string, ?INFO_TYPE:string, ?INFO_TEXT:string) is nondet
% maps to sql table
relation(xref, 8).
attribute(1, xref, xref_id, 'integer unsigned').
attribute(2, xref, external_db_id, smallint).
attribute(3, xref, dbprimary_acc, string).
attribute(4, xref, display_label, string).
attribute(5, xref, version, string).
attribute(6, xref, description, string).
attribute(7, xref, info_type, string).
attribute(8, xref, info_text, string).


/** <module> - Ensembl Core Schema Mapping

  ---+ Synopsis

  ==
  :- use_module(bio(sql_compiler)).
  :- use_module(bio(rdb_util)).
  :- use_module(bio('schema/schema_enscore51')).
  
  demo:-
    rdb_connect(H,homo_sapiens_core),
    rdb_forall(H,(   term(C,_,apoptosis,_,_,_),
                     term2term(_,_,C,SC,_),
                     term(SC,_,SCN,SCAcc,_,_)),
               format('~w "~w",[SCAcc,SCN])).
  ==
    
  ---+ Description

  ---+ See Also  

  * rdb_connect/2
  * sql_bind/2

  ---+ Changes from schema_enscore47
  
  http://www.ensembl.org/info/docs/api/funcgen/reg_features.html
  
  @author Chris Mungall
  @version  $Revision: 1.30 $
  @date  $Date: 2006/03/18 03:35:06 $
  @license LGPL

*/
