% Generated by sql-metadata command in blipkit_sql
:- discontiguous relation/2.
:- discontiguous attribute/3.


%% allele(?ALLELE_ID:integer unsigned, ?VARIATION_ID:integer unsigned, ?ALLELE:string, ?FREQUENCY:float, ?SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(allele, 5).
attribute(1, allele, allele_id, 'integer unsigned').
attribute(2, allele, variation_id, 'integer unsigned').
attribute(3, allele, allele, string).
attribute(4, allele, frequency, float).
attribute(5, allele, sample_id, 'integer unsigned').

%% allele_group(?ALLELE_GROUP_ID:integer unsigned, ?VARIATION_GROUP_ID:integer unsigned, ?SAMPLE_ID:integer unsigned, ?NAME:string, ?SOURCE_ID:integer unsigned, ?FREQUENCY:float) is nondet
% maps to sql table
relation(allele_group, 6).
attribute(1, allele_group, allele_group_id, 'integer unsigned').
attribute(2, allele_group, variation_group_id, 'integer unsigned').
attribute(3, allele_group, sample_id, 'integer unsigned').
attribute(4, allele_group, name, string).
attribute(5, allele_group, source_id, 'integer unsigned').
attribute(6, allele_group, frequency, float).

%% allele_group_allele(?ALLELE_GROUP_ID:integer unsigned, ?ALLELE:string, ?VARIATION_ID:integer unsigned) is nondet
% maps to sql table
relation(allele_group_allele, 3).
attribute(1, allele_group_allele, allele_group_id, 'integer unsigned').
attribute(2, allele_group_allele, allele, string).
attribute(3, allele_group_allele, variation_id, 'integer unsigned').

%% compressed_genotype_single_bp(?SAMPLE_ID:integer unsigned, ?SEQ_REGION_ID:integer unsigned, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?GENOTYPES:blob) is nondet
% maps to sql table
relation(compressed_genotype_single_bp, 6).
attribute(1, compressed_genotype_single_bp, sample_id, 'integer unsigned').
attribute(2, compressed_genotype_single_bp, seq_region_id, 'integer unsigned').
attribute(3, compressed_genotype_single_bp, seq_region_start, integer).
attribute(4, compressed_genotype_single_bp, seq_region_end, integer).
attribute(5, compressed_genotype_single_bp, seq_region_strand, tinyint).
attribute(6, compressed_genotype_single_bp, genotypes, blob).

%% failed_description(?FAILED_DESCRIPTION_ID:integer unsigned, ?DESCRIPTION:string) is nondet
% maps to sql table
relation(failed_description, 2).
attribute(1, failed_description, failed_description_id, 'integer unsigned').
attribute(2, failed_description, description, string).

%% failed_variation(?VARIATION_ID:integer unsigned, ?FAILED_DESCRIPTION_ID:integer unsigned) is nondet
% maps to sql table
relation(failed_variation, 2).
attribute(1, failed_variation, variation_id, 'integer unsigned').
attribute(2, failed_variation, failed_description_id, 'integer unsigned').

%% flanking_sequence(?VARIATION_ID:integer unsigned, ?UP_SEQ:string, ?DOWN_SEQ:string, ?UP_SEQ_REGION_START:integer, ?UP_SEQ_REGION_END:integer, ?DOWN_SEQ_REGION_START:integer, ?DOWN_SEQ_REGION_END:integer, ?SEQ_REGION_ID:integer unsigned, ?SEQ_REGION_STRAND:tinyint) is nondet
% maps to sql table
relation(flanking_sequence, 9).
attribute(1, flanking_sequence, variation_id, 'integer unsigned').
attribute(2, flanking_sequence, up_seq, string).
attribute(3, flanking_sequence, down_seq, string).
attribute(4, flanking_sequence, up_seq_region_start, integer).
attribute(5, flanking_sequence, up_seq_region_end, integer).
attribute(6, flanking_sequence, down_seq_region_start, integer).
attribute(7, flanking_sequence, down_seq_region_end, integer).
attribute(8, flanking_sequence, seq_region_id, 'integer unsigned').
attribute(9, flanking_sequence, seq_region_strand, tinyint).

%% httag(?HTTAG_ID:integer unsigned, ?VARIATION_GROUP_ID:integer unsigned, ?NAME:string, ?SOURCE_ID:integer unsigned) is nondet
% maps to sql table
relation(httag, 4).
attribute(1, httag, httag_id, 'integer unsigned').
attribute(2, httag, variation_group_id, 'integer unsigned').
attribute(3, httag, name, string).
attribute(4, httag, source_id, 'integer unsigned').

%% individual(?SAMPLE_ID:integer unsigned, ?GENDER:string, ?FATHER_INDIVIDUAL_SAMPLE_ID:integer unsigned, ?MOTHER_INDIVIDUAL_SAMPLE_ID:integer unsigned, ?INDIVIDUAL_TYPE_ID:integer unsigned) is nondet
% maps to sql table
relation(individual, 5).
attribute(1, individual, sample_id, 'integer unsigned').
attribute(2, individual, gender, string).
attribute(3, individual, father_individual_sample_id, 'integer unsigned').
attribute(4, individual, mother_individual_sample_id, 'integer unsigned').
attribute(5, individual, individual_type_id, 'integer unsigned').

%% individual_genotype_multiple_bp(?VARIATION_ID:integer unsigned, ?ALLELE_1:string, ?ALLELE_2:string, ?SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(individual_genotype_multiple_bp, 4).
attribute(1, individual_genotype_multiple_bp, variation_id, 'integer unsigned').
attribute(2, individual_genotype_multiple_bp, allele_1, string).
attribute(3, individual_genotype_multiple_bp, allele_2, string).
attribute(4, individual_genotype_multiple_bp, sample_id, 'integer unsigned').

%% individual_population(?INDIVIDUAL_SAMPLE_ID:integer unsigned, ?POPULATION_SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(individual_population, 2).
attribute(1, individual_population, individual_sample_id, 'integer unsigned').
attribute(2, individual_population, population_sample_id, 'integer unsigned').

%% individual_type(?INDIVIDUAL_TYPE_ID:integer unsigned, ?NAME:string, ?DESCRIPTION:string) is nondet
% maps to sql table
relation(individual_type, 3).
attribute(1, individual_type, individual_type_id, 'integer unsigned').
attribute(2, individual_type, name, string).
attribute(3, individual_type, description, string).

%% meta(?META_ID:integer unsigned, ?META_KEY:string, ?META_VALUE:string) is nondet
% maps to sql table
relation(meta, 3).
attribute(1, meta, meta_id, 'integer unsigned').
attribute(2, meta, meta_key, string).
attribute(3, meta, meta_value, string).

%% meta_coord(?TABLE_NAME:string, ?COORD_SYSTEM_ID:integer unsigned, ?MAX_LENGTH:integer) is nondet
% maps to sql table
relation(meta_coord, 3).
attribute(1, meta_coord, table_name, string).
attribute(2, meta_coord, coord_system_id, 'integer unsigned').
attribute(3, meta_coord, max_length, integer).

%% population(?SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(population, 1).
attribute(1, population, sample_id, 'integer unsigned').

%% population_genotype(?POPULATION_GENOTYPE_ID:integer unsigned, ?VARIATION_ID:integer unsigned, ?ALLELE_1:string, ?ALLELE_2:string, ?FREQUENCY:float, ?SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(population_genotype, 6).
attribute(1, population_genotype, population_genotype_id, 'integer unsigned').
attribute(2, population_genotype, variation_id, 'integer unsigned').
attribute(3, population_genotype, allele_1, string).
attribute(4, population_genotype, allele_2, string).
attribute(5, population_genotype, frequency, float).
attribute(6, population_genotype, sample_id, 'integer unsigned').

%% population_structure(?SUPER_POPULATION_SAMPLE_ID:integer unsigned, ?SUB_POPULATION_SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(population_structure, 2).
attribute(1, population_structure, super_population_sample_id, 'integer unsigned').
attribute(2, population_structure, sub_population_sample_id, 'integer unsigned').

%% read_coverage(?SEQ_REGION_ID:integer unsigned, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?LEVEL:tinyint, ?SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(read_coverage, 5).
attribute(1, read_coverage, seq_region_id, 'integer unsigned').
attribute(2, read_coverage, seq_region_start, integer).
attribute(3, read_coverage, seq_region_end, integer).
attribute(4, read_coverage, level, tinyint).
attribute(5, read_coverage, sample_id, 'integer unsigned').

%% sample(?SAMPLE_ID:integer unsigned, ?NAME:string, ?SIZE:integer, ?DESCRIPTION:string) is nondet
% maps to sql table
relation(sample, 4).
attribute(1, sample, sample_id, 'integer unsigned').
attribute(2, sample, name, string).
attribute(3, sample, size, integer).
attribute(4, sample, description, string).

%% sample_synonym(?SAMPLE_SYNONYM_ID:integer unsigned, ?SAMPLE_ID:integer unsigned, ?SOURCE_ID:integer unsigned, ?NAME:string) is nondet
% maps to sql table
relation(sample_synonym, 4).
attribute(1, sample_synonym, sample_synonym_id, 'integer unsigned').
attribute(2, sample_synonym, sample_id, 'integer unsigned').
attribute(3, sample_synonym, source_id, 'integer unsigned').
attribute(4, sample_synonym, name, string).

%% source(?SOURCE_ID:integer unsigned, ?NAME:string, ?VERSION:integer) is nondet
% maps to sql table
relation(source, 3).
attribute(1, source, source_id, 'integer unsigned').
attribute(2, source, name, string).
attribute(3, source, version, integer).

%% tagged_variation_feature(?VARIATION_FEATURE_ID:integer unsigned, ?SAMPLE_ID:integer unsigned) is nondet
% maps to sql table
relation(tagged_variation_feature, 2).
attribute(1, tagged_variation_feature, variation_feature_id, 'integer unsigned').
attribute(2, tagged_variation_feature, sample_id, 'integer unsigned').

%% transcript_variation(?TRANSCRIPT_VARIATION_ID:integer unsigned, ?TRANSCRIPT_ID:integer unsigned, ?VARIATION_FEATURE_ID:integer unsigned, ?CDNA_START:integer, ?CDNA_END:integer, ?TRANSLATION_START:integer, ?TRANSLATION_END:integer, ?PEPTIDE_ALLELE_STRING:string, ?CONSEQUENCE_TYPE:string) is nondet
% maps to sql table
relation(transcript_variation, 9).
attribute(1, transcript_variation, transcript_variation_id, 'integer unsigned').
attribute(2, transcript_variation, transcript_id, 'integer unsigned').
attribute(3, transcript_variation, variation_feature_id, 'integer unsigned').
attribute(4, transcript_variation, cdna_start, integer).
attribute(5, transcript_variation, cdna_end, integer).
attribute(6, transcript_variation, translation_start, integer).
attribute(7, transcript_variation, translation_end, integer).
attribute(8, transcript_variation, peptide_allele_string, string).
attribute(9, transcript_variation, consequence_type, string).

%% variation(?VARIATION_ID:integer unsigned, ?SOURCE_ID:integer unsigned, ?NAME:string, ?VALIDATION_STATUS:string, ?ANCESTRAL_ALLELE:string) is nondet
% maps to sql table
relation(variation, 5).
attribute(1, variation, variation_id, 'integer unsigned').
attribute(2, variation, source_id, 'integer unsigned').
attribute(3, variation, name, string).
attribute(4, variation, validation_status, string).
attribute(5, variation, ancestral_allele, string).

%% variation_feature(?VARIATION_FEATURE_ID:integer unsigned, ?SEQ_REGION_ID:integer unsigned, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?VARIATION_ID:integer unsigned, ?ALLELE_STRING:string, ?VARIATION_NAME:string, ?MAP_WEIGHT:integer, ?FLAGS:string, ?SOURCE_ID:integer unsigned, ?VALIDATION_STATUS:string, ?CONSEQUENCE_TYPE:string) is nondet
% maps to sql table
relation(variation_feature, 13).
attribute(1, variation_feature, variation_feature_id, 'integer unsigned').
attribute(2, variation_feature, seq_region_id, 'integer unsigned').
attribute(3, variation_feature, seq_region_start, integer).
attribute(4, variation_feature, seq_region_end, integer).
attribute(5, variation_feature, seq_region_strand, tinyint).
attribute(6, variation_feature, variation_id, 'integer unsigned').
attribute(7, variation_feature, allele_string, string).
attribute(8, variation_feature, variation_name, string).
attribute(9, variation_feature, map_weight, integer).
attribute(10, variation_feature, flags, string).
attribute(11, variation_feature, source_id, 'integer unsigned').
attribute(12, variation_feature, validation_status, string).
attribute(13, variation_feature, consequence_type, string).

%% variation_group(?VARIATION_GROUP_ID:integer unsigned, ?NAME:string, ?SOURCE_ID:integer unsigned, ?TYPE:string) is nondet
% maps to sql table
relation(variation_group, 4).
attribute(1, variation_group, variation_group_id, 'integer unsigned').
attribute(2, variation_group, name, string).
attribute(3, variation_group, source_id, 'integer unsigned').
attribute(4, variation_group, type, string).

%% variation_group_feature(?VARIATION_GROUP_FEATURE_ID:integer unsigned, ?SEQ_REGION_ID:integer unsigned, ?SEQ_REGION_START:integer, ?SEQ_REGION_END:integer, ?SEQ_REGION_STRAND:tinyint, ?VARIATION_GROUP_ID:integer unsigned, ?VARIATION_GROUP_NAME:string) is nondet
% maps to sql table
relation(variation_group_feature, 7).
attribute(1, variation_group_feature, variation_group_feature_id, 'integer unsigned').
attribute(2, variation_group_feature, seq_region_id, 'integer unsigned').
attribute(3, variation_group_feature, seq_region_start, integer).
attribute(4, variation_group_feature, seq_region_end, integer).
attribute(5, variation_group_feature, seq_region_strand, tinyint).
attribute(6, variation_group_feature, variation_group_id, 'integer unsigned').
attribute(7, variation_group_feature, variation_group_name, string).

%% variation_group_variation(?VARIATION_ID:integer unsigned, ?VARIATION_GROUP_ID:integer unsigned) is nondet
% maps to sql table
relation(variation_group_variation, 2).
attribute(1, variation_group_variation, variation_id, 'integer unsigned').
attribute(2, variation_group_variation, variation_group_id, 'integer unsigned').

%% variation_synonym(?VARIATION_SYNONYM_ID:integer unsigned, ?VARIATION_ID:integer unsigned, ?SOURCE_ID:integer unsigned, ?NAME:string, ?MOLTYPE:string) is nondet
% maps to sql table
relation(variation_synonym, 5).
attribute(1, variation_synonym, variation_synonym_id, 'integer unsigned').
attribute(2, variation_synonym, variation_id, 'integer unsigned').
attribute(3, variation_synonym, source_id, 'integer unsigned').
attribute(4, variation_synonym, name, string).
attribute(5, variation_synonym, moltype, string).
