 % -- ********************************************************* --
 % -- Autogenerated Prolog factfiles 
 % -- see http://www.blipkit.org for details 
 % -- ********************************************************* --


class('GO:0060600').
metadata_db:entity_synonym('GO:0060600', 'dichotomous subdivision of terminal units').
metadata_db:entity_synonym_scope('GO:0060600', 'dichotomous subdivision of terminal units', 'exact').

class('GO:0060601').
metadata_db:entity_synonym('GO:0060601', 'lateral sprouting').
metadata_db:entity_synonym_scope('GO:0060601', 'lateral sprouting', 'exact').

class('GO:0060602').
metadata_db:entity_synonym('GO:0060602', 'epithelial cord elongation').
metadata_db:entity_synonym_scope('GO:0060602', 'epithelial cord elongation', 'exact').

class('GO:0008305').
metadata_db:entity_synonym('GO:0008305', 'integrin').
metadata_db:entity_synonym_scope('GO:0008305', 'integrin', 'exact').

class('GO:0008045').
metadata_db:entity_synonym('GO:0008045', 'motor neuron axon guidance').
metadata_db:entity_synonym_scope('GO:0008045', 'motor neuron axon guidance', 'exact').

class('GO:0007160').
metadata_db:entity_synonym('GO:0007160', 'cell-extracellular matrix adhesion').
metadata_db:entity_synonym_scope('GO:0007160', 'cell-extracellular matrix adhesion', 'exact').

class('GO:0043046').
metadata_db:entity_synonym('GO:0043046', 'DNA methylation during gamete generation').
metadata_db:entity_synonym_scope('GO:0043046', 'DNA methylation during gamete generation', 'exact').

class('GO:0015934').
metadata_db:entity_synonym('GO:0015934', 'ribosomal large subunit').
metadata_db:entity_synonym_scope('GO:0015934', 'ribosomal large subunit', 'exact').

class('GO:0005575').
metadata_db:entity_synonym('GO:0005575', 'cellular component').
metadata_db:entity_synonym_scope('GO:0005575', 'cellular component', 'exact').

class('GO:0009950').
metadata_db:entity_synonym('GO:0009950', 'dorsal/ventral axis determination').
metadata_db:entity_synonym_scope('GO:0009950', 'dorsal/ventral axis determination', 'exact').

class('GO:0030154').
metadata_db:entity_synonym('GO:0030154', 'differentiation').
metadata_db:entity_synonym_scope('GO:0030154', 'differentiation', 'exact').

class('GO:0001831').
metadata_db:entity_synonym('GO:0001831', 'trophectodermal cell morphogenesis').
metadata_db:entity_synonym_scope('GO:0001831', 'trophectodermal cell morphogenesis', 'exact').

class('GO:0005794').
metadata_db:entity_synonym('GO:0005794', 'Golgi').
metadata_db:entity_synonym_scope('GO:0005794', 'Golgi', 'exact').

metadata_db:entity_resource('CHEBI:29108', 'chebi_ontology').
class('CHEBI:29108').
metadata_db:entity_synonym('CHEBI:29108', 'calcium ion').
metadata_db:entity_synonym_scope('CHEBI:29108', 'calcium ion', 'exact').
metadata_db:entity_synonym('CHEBI:29108', 'calcium ions').
metadata_db:entity_synonym_scope('CHEBI:29108', 'calcium ions', 'exact').

metadata_db:entity_resource('CHEBI:24431', 'chebi_ontology').
class('CHEBI:24431').
metadata_db:entity_synonym('CHEBI:24431', 'chemical substance').
metadata_db:entity_synonym_scope('CHEBI:24431', 'chemical substance', 'exact').

class('FBbt:00004508').
metadata_db:entity_synonym('FBbt:00004508', 'compound eye').
metadata_db:entity_synonym_scope('FBbt:00004508', 'compound eye', 'exact').

class('ZFA:0000107').
metadata_db:entity_synonym('ZFA:0000107', 'camera-type eye').
metadata_db:entity_synonym_scope('ZFA:0000107', 'camera-type eye', 'exact').

class('XAO:0000179').
metadata_db:entity_synonym('XAO:0000179', 'eye').
metadata_db:entity_synonym_scope('XAO:0000179', 'eye', 'exact').
metadata_db:entity_synonym('XAO:0000179', 'camera-type eye').
metadata_db:entity_synonym_scope('XAO:0000179', 'camera-type eye', 'exact').

class('MA:0000261').
metadata_db:entity_synonym('MA:0000261', 'camera-type eye').
metadata_db:entity_synonym_scope('MA:0000261', 'camera-type eye', 'exact').

class('FMA:12513').
metadata_db:entity_synonym('FMA:12513', 'camera-type eye').
metadata_db:entity_synonym_scope('FMA:12513', 'camera-type eye', 'exact').

class('bfo:Role').

metadata_db:entity_label('obol:culmination', 'culmination').
class('obol:culmination').
subclass('obol:culmination', 'GO:0008150').

metadata_db:entity_label('obol:symbiont', 'symbiont').
class('obol:symbiont').
subclass('obol:symbiont', 'bfo:Role').

metadata_db:entity_label('obol:other_organism', 'other organism').
class('obol:other_organism').
subclass('obol:other_organism', 'bfo:Role').

metadata_db:entity_label('obol:organism', 'organism').
class('obol:organism').
subclass('obol:organism', 'bfo:Role').

metadata_db:entity_label('obol:host', 'host').
class('obol:host').
subclass('obol:host', 'bfo:Role').

metadata_db:entity_label('obol:parasite', 'parasite').
class('obol:parasite').
subclass('obol:parasite', 'bfo:Role').

metadata_db:entity_label('obol:antigen', 'antigen').
class('obol:antigen').
subclass('obol:antigen', 'bfo:Role').

metadata_db:entity_label('obol:superantigen', 'superantigen').
class('obol:superantigen').
subclass('obol:superantigen', 'bfo:Role').

metadata_db:entity_label('obol:self_antigen', 'self antigen').
class('obol:self_antigen').
subclass('obol:self_antigen', 'bfo:Role').

metadata_db:entity_label('obol:electron_donor', 'electron donor').
class('obol:electron_donor').
subclass('obol:electron_donor', 'bfo:Role').

metadata_db:entity_label('obol:solute', 'solute').
class('obol:solute').
subclass('obol:solute', 'bfo:Role').

metadata_db:entity_label('obol:solvent', 'solvent').
class('obol:solvent').
subclass('obol:solvent', 'bfo:Role').

