:- use_module(bio(phylo_db)).
:- use_module(bio(phylo_xmlmap_phyloxml)).
:- use_module(bio(phylo_bridge_from_taxon)).
:- use_module(bio(phylo_writer_chadoxml)).
:- use_module(bio(phylo_bridge_to_ontol)).
:- use_module(bio(phylo_sqlmap_chado)).
:- use_module(bio(phylo_sqlmap_enscompara)).
:- use_module(bio(parser_nhx)).
:- use_module(bio(homol_db)).
:- use_module(bio(homol_xmlmap_homologene)).
:- use_module(bio(homol_bridge_from_ontol)).
:- use_module(bio(homol_bridge_to_ontol)).
:- use_module(bio(homol_sqlmap_go)).
:- use_module(bio(homoltbl_bridge_to_homol)).
