% interaction('INTERACTOR_A', 'INTERACTOR_B', 'OFFICIAL_SYMBOL_A', 'OFFICIAL_SYMBOL_B', 'ALIASES_FOR_A', 'ALIASES_FOR_B', 'EXPERIMENTAL_SYSTEM', 'SOURCE', 'PUBMED_ID', 'ORGANISM_A_ID', 'ORGANISM_B_ID').

