:- [bio(obol_biological_process_xp_cellular_component)].
:- [bio(obol_biological_process_xp_cell)].
:- [bio(obol_biological_process_xp_chemical)].
:- [bio(obol_biological_process_xp_quality)].
:- [bio(obol_biological_process_xp_function)].
:- [bio(obol_biological_process_xp_anatomy)].
:- [bio(obol_biological_process_xp_self)].
:- [bio(obol_cellular_component_xp_cell)].
:- [bio(obol_cellular_component_xp_function)].
