:- module(ontol_manifest_cdef_from_chebi_formula,[]).

:- use_module(bio(ontol_db)).
:- use_module(bio(metadata_db)).
:- use_module(bio(tabling)).

%class_formula_elts(C,Formula,cdef('CHEBI:24431',Diffs)) :-
class_formula_elts(C,Formula,Elts) :-
        entity_synonym_type(C,Formula,'FORMULA'),
        atom_codes(Formula,Codes),
        formula(Elts,Codes,[]),
        Elts\=[],
        Elts\=[_-1].

:- table_pred(class_formula_elts/3).

ontol_db:subclass(X,FID) :-
        class_formula_elts(X,Formula,_),
        formula_id(Formula,FID).

ontol_db:class(FID) :-
        class_formula_elts(_,Formula,_),
        formula_id(Formula,FID).

metadata_db:entity_resource(FID,formula) :-
        class_formula_elts(_,Formula,_),
        formula_id(Formula,FID).

ontol_db:genus(FID,'CHEBI:24431') :-
        class_formula_elts(_,Formula,_),
        formula_id(Formula,FID).

ontol_db:differentium(FID,card(has_part,Num,Num),E) :-
        class_formula_elts(_,Formula,Elts),
        formula_id(Formula,FID),
        member(E-Num,Elts).

formula_id(Formula,FID) :-
        atom_concat('FORMULA:',Formula,FID).

formula([X|L]) --> eltnum(X),!,formula(L).
formula([]) --> [].

eltnum(E-Num) --> elt(E),num(Num),!.
eltnum(E-1) --> elt(E).

num(Num) --> numcodes(Codes),{Codes\=[],atom_codes(A,Codes),atom_number(A,Num)}.

numcodes([D|L]) --> dig(D),!,numcodes(L).
numcodes([]) --> [].


dig(D) --> [D],{D >= 48, D =< 57}.

% autogenerated like this:
% blip -r chebi -u ontol_db findall "(subclassT(X,'CHEBI:33250'),entity_synonym_type(X,S,'FORMULA'),class(X,N),format('elt(~q) --> #~w#. % ~w~n',[X,S,N]))"

elt('CHEBI:18248') --> "Fe". % iron
elt('CHEBI:18291') --> "Mn". % manganese
elt('CHEBI:22927') --> "Br". % bromine
elt('CHEBI:22977') --> "Cd". % cadmium
elt('CHEBI:22984') --> "Ca". % calcium
elt('CHEBI:23116') --> "Cl". % chlorine
elt('CHEBI:24061') --> "F". % fluorine
elt('CHEBI:24859') --> "I". % iodine
elt('CHEBI:25016') --> "Pb". % lead
elt('CHEBI:25107') --> "Mg". % magnesium
elt('CHEBI:25195') --> "Hg". % mercury
elt('CHEBI:25555') --> "N". % nitrogen
elt('CHEBI:25805') --> "O". % oxygen
elt('CHEBI:26216') --> "K". % potassium
elt('CHEBI:26708') --> "Na". % sodium
elt('CHEBI:26833') --> "S". % sulfur
elt('CHEBI:27007') --> "Sn". % tin
elt('CHEBI:27214') --> "U". % uranium
elt('CHEBI:27363') --> "Zn". % zinc
elt('CHEBI:27563') --> "As". % arsenic
elt('CHEBI:27568') --> "Se". % selenium
elt('CHEBI:27573') --> "Si". % silicon
elt('CHEBI:27594') --> "C". % carbon
elt('CHEBI:27638') --> "Co". % cobalt
elt('CHEBI:27698') --> "V". % vanadium
elt('CHEBI:27998') --> "W". % tungsten
elt('CHEBI:28073') --> "Cr". % chromium
elt('CHEBI:28112') --> "Ni". % nickel
elt('CHEBI:28659') --> "P". % phosphorus
elt('CHEBI:28685') --> "Mo". % molybdenum
elt('CHEBI:28694') --> "Cu". % copper
elt('CHEBI:28984') --> "Al". % aluminium
elt('CHEBI:29237') --> "D". % deuterium
elt('CHEBI:29238') --> "T". % tritium
elt('CHEBI:29287') --> "Au". % gold
elt('CHEBI:30145') --> "Li". % lithium
elt('CHEBI:30217') --> "He". % helium
elt('CHEBI:30415') --> "At". % astatine
elt('CHEBI:30430') --> "In". % indium
elt('CHEBI:30441') --> "Ge". % germanium
elt('CHEBI:30452') --> "Te". % tellurium
elt('CHEBI:30501') --> "Be". % beryllium
elt('CHEBI:30512') --> "Ag". % silver
elt('CHEBI:30513') --> "Sb". % antimony
elt('CHEBI:30514') --> "Cs". % caesium
elt('CHEBI:30682') --> "Ru". % ruthenium
elt('CHEBI:30687') --> "Os". % osmium
elt('CHEBI:32594') --> "Ba". % barium
elt('CHEBI:32999') --> "Eu". % europium
elt('CHEBI:33301') --> "Bi". % bismuth
elt('CHEBI:33310') --> "Ne". % neon
elt('CHEBI:33313') --> "Po". % polonium
elt('CHEBI:33314') --> "Rn". % radon
elt('CHEBI:33322') --> "Rb". % rubidium
elt('CHEBI:33323') --> "Fr". % francium
elt('CHEBI:33324') --> "Sr". % strontium
elt('CHEBI:33325') --> "Ra". % radium
elt('CHEBI:33330') --> "Sc". % scandium
elt('CHEBI:33331') --> "Y". % yttrium
elt('CHEBI:33336') --> "La". % lanthanum
elt('CHEBI:33337') --> "Ac". % actinium
elt('CHEBI:33341') --> "Ti". % titanium
elt('CHEBI:33342') --> "Zr". % zirconium
elt('CHEBI:33343') --> "Hf". % hafnium
elt('CHEBI:33344') --> "Nb". % niobium
elt('CHEBI:33346') --> "Rf". % rutherfordium
elt('CHEBI:33348') --> "Ta". % tantalum
elt('CHEBI:33349') --> "Db". % dubnium
elt('CHEBI:33351') --> "Sg". % seaborgium
elt('CHEBI:33353') --> "Tc". % technetium
elt('CHEBI:33355') --> "Bh". % bohrium
elt('CHEBI:33357') --> "Hs". % hassium
elt('CHEBI:33359') --> "Rh". % rhodium
elt('CHEBI:33361') --> "Mt". % meitnerium
elt('CHEBI:33363') --> "Pd". % palladium
elt('CHEBI:33364') --> "Pt". % platinum
elt('CHEBI:33367') --> "Ds". % darmstadtium
elt('CHEBI:33368') --> "Rg". % roentgenium
elt('CHEBI:33369') --> "Ce". % cerium
elt('CHEBI:33372') --> "Nd". % neodymium
elt('CHEBI:33373') --> "Pm". % promethium
elt('CHEBI:33374') --> "Sm". % samarium
elt('CHEBI:33375') --> "Gd". % gadolinium
elt('CHEBI:33376') --> "Tb". % terbium
elt('CHEBI:33377') --> "Dy". % dysprosium
elt('CHEBI:33379') --> "Er". % erbium
elt('CHEBI:33381') --> "Yb". % ytterbium
elt('CHEBI:33382') --> "Lu". % lutetium
elt('CHEBI:33385') --> "Th". % thorium
elt('CHEBI:33386') --> "Pa". % protactinium
elt('CHEBI:33387') --> "Np". % neptunium
elt('CHEBI:33388') --> "Pu". % plutonium
elt('CHEBI:33389') --> "Am". % americium
elt('CHEBI:33391') --> "Bk". % berkelium
elt('CHEBI:33392') --> "Cf". % californium
elt('CHEBI:33393') --> "Es". % einsteinium
elt('CHEBI:33394') --> "Fm". % fermium
elt('CHEBI:33395') --> "Md". % mendelevium
elt('CHEBI:33396') --> "No". % nobelium
elt('CHEBI:33397') --> "Lr". % lawrencium
elt('CHEBI:49475') --> "Ar". % argon
elt('CHEBI:49631') --> "Ga". % gallium
elt('CHEBI:49637') --> "H". % hydrogen
elt('CHEBI:49648') --> "Ho". % holmium
elt('CHEBI:49666') --> "Ir". % iridium
elt('CHEBI:49696') --> "Kr". % krypton
elt('CHEBI:49828') --> "Pr". % praseodymium
elt('CHEBI:49882') --> "Re". % rhenium
elt('CHEBI:49957') --> "Xe". % xenon
elt('CHEBI:33390') --> "Cm". % curium
elt('CHEBI:27560') --> "B". % boron
elt('CHEBI:30440') --> "Tl". % thallium
elt('CHEBI:33380') --> "Tm". % thulium


/** <module> 

  ---+ Synopsis

==
:- use_module(bio(ontol_manifest_cdef_from_chebi_formula)).

% 
demo:-
  nl.
  

==

---+ Details



---+ Additional Information

This module is part of blip. For more details, see http://www.blipkit.org

@author  Chris Mungall
@version $Revision$
@see     README
@license License


*/
