% Generated by sql-metadata command in blipkit_sql
:- discontiguous relation/2.
:- discontiguous attribute/3.
:- discontiguous unique/2.
%% IMPORTANT: unique/2 must be entered MANUALLY - cannot introspect

%% adenine(?B:string) is nondet
% maps to sql table
relation(adenine, 1).
attribute(1, adenine, b, string).
unique(adenine,b).


%% cytosine(?B:string) is nondet
% maps to sql table
relation(cytosine, 1).
attribute(1, cytosine, b, string).
unique(cytosine,b).

%% uracil(?B:string) is nondet
% maps to sql table
relation(uracil, 1).
attribute(1, uracil, b, string).
unique(uracil,b).

%% guanine(?B:string) is nondet
% maps to sql table
relation(guanine, 1).
attribute(1, guanine, b, string).
unique(guanine,b).

%% five_prime_to(?B:string, ?TARGET:string) is nondet
% maps to sql table
relation(five_prime_to, 2).
attribute(1, five_prime_to, b, string).
attribute(2, five_prime_to, target, string).


%% pairs_with_cww(?B:string, ?TARGET:string) is nondet
% maps to sql table
relation(pairs_with_cww, 2).
attribute(1, pairs_with_cww, b, string).
attribute(2, pairs_with_cww, target, string).

%% purine(?B:string) is nondet
% maps to sql view
relation(purine, 1).
attribute(1, purine, b, string).
unique(purine,b).

%% pyrimidine(?B:string) is nondet
% maps to sql view
relation(pyrimidine, 1).
attribute(1, pyrimidine, b, string).
unique(pyrimidine,b).
