:- use_module(library('semweb/rdf_db')).

% new
:- rdf_register_ns('IDO','http://purl.obolibrary.org/obo/IDO_',[force(true)]).

:- rdf_register_ns('MA','http://purl.org/obo/owl/MA#MA_',[force(true)]).
:- rdf_register_ns('AAO','http://purl.org/obo/owl/AAO#AAO_',[force(true)]).
:- rdf_register_ns('ADW','http://purl.org/obo/owl/ADW#ADW_',[force(true)]).
:- rdf_register_ns('PATO','http://purl.org/obo/owl/PATO#PATO_',[force(true)]).
:- rdf_register_ns('BILA','http://purl.org/obo/owl/BILA#BILA_',[force(true)]).
:- rdf_register_ns('GO','http://purl.org/obo/owl/GO#GO_',[force(true)]).
:- rdf_register_ns('BTO','http://purl.org/obo/owl/BTO#BTO_',[force(true)]).
:- rdf_register_ns('CARO','http://purl.org/obo/owl/CARO#CARO_',[force(true)]).
:- rdf_register_ns('BSPO','http://purl.org/obo/owl/BSPO#BSPO_',[force(true)]).
:- rdf_register_ns('SPD','http://purl.org/obo/owl/SPD#SPD_',[force(true)]).
:- rdf_register_ns('CL','http://purl.org/obo/owl/CL#CL_',[force(true)]).
:- rdf_register_ns('GO','http://purl.org/obo/owl/GO#GO_',[force(true)]).
:- rdf_register_ns('CHEBI','http://purl.org/obo/owl/CHEBI#CHEBI_',[force(true)]).
:- rdf_register_ns('RESID','http://purl.org/obo/owl/RESID#RESID_',[force(true)]).
:- rdf_register_ns('DDANAT','http://purl.org/obo/owl/DDANAT#DDANAT_',[force(true)]).
:- rdf_register_ns('DOID','http://purl.org/obo/owl/DOID#DOID_',[force(true)]).
:- rdf_register_ns('EMAP','http://purl.org/obo/owl/EMAP#EMAP_',[force(true)]).
:- rdf_register_ns('ENVO','http://purl.org/obo/owl/ENVO#ENVO_',[force(true)]).
:- rdf_register_ns('IEV','http://purl.org/obo/owl/IEV#IEV_',[force(true)]).
:- rdf_register_ns('ECO','http://purl.org/obo/owl/ECO#ECO_',[force(true)]).
:- rdf_register_ns('EV','http://purl.org/obo/owl/EV#EV_',[force(true)]).
:- rdf_register_ns('FIX','http://purl.org/obo/owl/FIX#FIX_',[force(true)]).
:- rdf_register_ns('FBbt','http://purl.org/obo/owl/FBbt#FBbt_',[force(true)]).
:- rdf_register_ns('FBdv','http://purl.org/obo/owl/FBdv#FBdv_',[force(true)]).
:- rdf_register_ns('FBsp','http://purl.org/obo/owl/FBsp#FBsp_',[force(true)]).
:- rdf_register_ns('FBcv','http://purl.org/obo/owl/FBcv#FBcv_',[force(true)]).
:- rdf_register_ns('FMA','http://purl.org/obo/owl/FMA#FMA_',[force(true)]).
:- rdf_register_ns('FAO','http://purl.org/obo/owl/FAO#FAO_',[force(true)]).
:- rdf_register_ns('YPO','http://purl.org/obo/owl/YPO#YPO_',[force(true)]).
:- rdf_register_ns('BOOTStrep','http://purl.org/obo/owl/BOOTStrep#BOOTStrep_',[force(true)]).
:- rdf_register_ns('EHDAA','http://purl.org/obo/owl/EHDAA#EHDAA_',[force(true)]).
:- rdf_register_ns('EHDA','http://purl.org/obo/owl/EHDA#EHDA_',[force(true)]).
:- rdf_register_ns('HP','http://purl.org/obo/owl/HP#HP_',[force(true)]).
:- rdf_register_ns('FBbi','http://purl.org/obo/owl/FBbi#FBbi_',[force(true)]).
:- rdf_register_ns('IPR','http://purl.org/obo/owl/IPR#IPR_',[force(true)]).
:- rdf_register_ns('MP','http://purl.org/obo/owl/MP#MP_',[force(true)]).
:- rdf_register_ns('RO','http://purl.org/obo/owl/RO#RO_',[force(true)]).
:- rdf_register_ns('MFO','http://purl.org/obo/owl/MFO#MFO_',[force(true)]).
:- rdf_register_ns('MO','http://purl.org/obo/owl/MO#MO_',[force(true)]).
:- rdf_register_ns('GO','http://purl.org/obo/owl/GO#GO_',[force(true)]).
:- rdf_register_ns('IMR','http://purl.org/obo/owl/IMR#IMR_',[force(true)]).
:- rdf_register_ns('TGMA','http://purl.org/obo/owl/TGMA#TGMA_',[force(true)]).
:- rdf_register_ns('MIRO','http://purl.org/obo/owl/MIRO#MIRO_',[force(true)]).
:- rdf_register_ns('MPATH','http://purl.org/obo/owl/MPATH#MPATH_',[force(true)]).
:- rdf_register_ns('NCBITaxon','http://purl.org/obo/owl/NCBITaxon#NCBITaxon_',[force(true)]).
:- rdf_register_ns('NCIt','http://purl.org/obo/owl/NCIt#NCIt_',[force(true)]).
:- rdf_register_ns('NEWT','http://purl.org/obo/owl/NEWT#NEWT_',[force(true)]).
:- rdf_register_ns('NMR','http://purl.org/obo/owl/NMR#NMR_',[force(true)]).
:- rdf_register_ns('PW','http://purl.org/obo/owl/PW#PW_',[force(true)]).
:- rdf_register_ns('EO','http://purl.org/obo/owl/EO#EO_',[force(true)]).
:- rdf_register_ns('TO','http://purl.org/obo/owl/TO#TO_',[force(true)]).
:- rdf_register_ns('PLO','http://purl.org/obo/owl/PLO#PLO_',[force(true)]).
:- rdf_register_ns('PO','http://purl.org/obo/owl/PO#PO_',[force(true)]).
:- rdf_register_ns('PO','http://purl.org/obo/owl/PO#PO_',[force(true)]).
:- rdf_register_ns('PRO','http://purl.org/obo/owl/PRO#PRO_',[force(true)]).
:- rdf_register_ns('ProPreO','http://purl.org/obo/owl/ProPreO#ProPreO_',[force(true)]).
:- rdf_register_ns('MI','http://purl.org/obo/owl/MI#MI_',[force(true)]).
:- rdf_register_ns('MOD','http://purl.org/obo/owl/MOD#MOD_',[force(true)]).
:- rdf_register_ns('MS','http://purl.org/obo/owl/MS#MS_',[force(true)]).
%:- rdf_register_ns('OBO_REL','http://purl.org/obo/owl/OBO_REL#',[force(true)]).
:- rdf_register_ns('REX','http://purl.org/obo/owl/REX#REX_',[force(true)]).
:- rdf_register_ns('SEP','http://purl.org/obo/owl/SEP#SEP_',[force(true)]).
:- rdf_register_ns('SO','http://purl.org/obo/owl/SO#SO_',[force(true)]).
:- rdf_register_ns('SBO','http://purl.org/obo/owl/SBO#SBO_',[force(true)]).
:- rdf_register_ns('SOPHARM','http://purl.org/obo/owl/SOPHARM#SOPHARM_',[force(true)]).
:- rdf_register_ns('TAO','http://purl.org/obo/owl/TAO#TAO_',[force(true)]).
:- rdf_register_ns('TTO','http://purl.org/obo/owl/TTO#TTO_',[force(true)]).
:- rdf_register_ns('TRANS','http://purl.org/obo/owl/TRANS#TRANS_',[force(true)]).
:- rdf_register_ns('GRO','http://purl.org/obo/owl/GRO#GRO_',[force(true)]).
:- rdf_register_ns('GRO','http://purl.org/obo/owl/GRO#GRO_',[force(true)]).
:- rdf_register_ns('TADS','http://purl.org/obo/owl/TADS#TADS_',[force(true)]).
:- rdf_register_ns('UBERON','http://purl.org/obo/owl/UBERON#UBERON_',[force(true)]).
:- rdf_register_ns('UO','http://purl.org/obo/owl/UO#UO_',[force(true)]).
:- rdf_register_ns('WBbt','http://purl.org/obo/owl/WBbt#WBbt_',[force(true)]).
:- rdf_register_ns('WBls','http://purl.org/obo/owl/WBls#WBls_',[force(true)]).
:- rdf_register_ns('WBPhenotype','http://purl.org/obo/owl/WBPhenotype#WBPhenotype_',[force(true)]).
:- rdf_register_ns('XAO','http://purl.org/obo/owl/XAO#XAO_',[force(true)]).
:- rdf_register_ns('ZEA','http://purl.org/obo/owl/ZEA#ZEA_',[force(true)]).
:- rdf_register_ns('ZFA','http://purl.org/obo/owl/ZFA#ZFA_',[force(true)]).
