'HTML'(version='-//W3C//DTD HTML 4.0 Transitional//EN',
       html(lang=en,
            head(title('AmiGO! Your friend in the Gene Ontology.'),
                 meta('http-equiv'='content-type', content='text/html; charset=iso-8859-1',
                      meta(name=html_url, content='http://amigo.geneontology.org/amigo',
                           link(href='http://amigo.geneontology.org/amigo/css/formatting.css', rel=stylesheet, type='text/css',
                                script(type='text/javascript', src='http://yui.yahooapis.com/2.3.1/build/yahoo-dom-event/yahoo-dom-event.js'),
                                script(type='text/javascript', src='http://amigo.geneontology.org/amigo/js/all.js'),
                                style(type='text/css'))))),
            
            body(div(id=header, a(class='logo floatR', href='search.cgi?session_id=6010amigo1231635692', img(src='http://amigo.geneontology.org/amigo/images/logo-sm.png', alt='AmiGO logo', title='AmiGO front page')), h1(id=top, a(href='http://www.geneontology.org/', title='Gene Ontology website', 'the Gene Ontology'))),
                 div(id=searchbar, ul(id=menuToggle, li(a(href='search.cgi?action=advanced_query&session_id=6010amigo1231635692', title='Advanced search for GO terms or gene product annotations', 'Search')), li(a(href='browse.cgi?session_id=6010amigo1231635692', title='Browse the terms in the Gene Ontology', 'Browse')), li(a(href='blast.cgi?session_id=6010amigo1231635692', title='BLAST search for gene products', 'BLAST')), li(a(href=term_enrichment, title='Find significant terms in the GO', 'Term Enrichment')), li(a(href=slimmer, title='Map your data to high level terms', 'GO Slimmer')), li(a(href='http://www.berkeleybop.org/goose', title='GO Online SQL Environment: query the GO database directly', 'GOOSE')), li(a(href='http://www.geneontology.org/amigo/help-front.shtml', title='Help guide for this page', 'Help')))),
                 div(class=contents, form(action='search.cgi', name=frontForm, id=frontForm, method='POST', fieldset(class='C', legend('Search'), input(type=hidden, name=session_id, value='6010amigo1231635692', p(label(for=query, 'Search the Gene Ontology database')), input(type=text, name=search_query, size='55', value='', class=textBox, id=query, input(type=hidden, name=action, value='new-search', fieldset(legend('Search type'), span(input(type=radio, name=search_constraint, value=term, label(for=term, 'GO terms'))), span(input(type=radio, name=search_constraint, value=gp, id=gp, label(for=gp, 'genes or proteins'))), input(type=checkbox, id=exact_match, name=exact_match, value=yes, label(for=exact_match, 'exact match'))), input(class=button, type=submit))))))),
                 div(id=footer, p('GO database release 2009-01-08', br(a(href='http://www.geneontology.org/GO.cite.shtml#data', title='How to cite AmiGO data', 'Cite this data'), '•', a(href='http://www.geneontology.org/GO.cite.shtml', title='Terms of use for the GO project', 'Terms of use'), '•', a(href='http://www.geneontology.org/GO.contacts.shtml', title='Contact the GO helpdesk', 'GO helpdesk'), br('Copyright © 1999-2008', a(href='http://www.geneontology.org/index.shtml', title='Gene Ontology home page', 'the Gene Ontology'))))))))
