#!/usr/bin/perl

my $PROLOGDOC = shift @ARGV;
my @modules = @ARGV;
my @sources = map {"lib/$_.pro"} @modules;
run("pldoc --to doc/pdoc --driver pldoc --pl-ext pro @sources");
foreach (@modules) {
    run("xsltproc --stringparam sourcedir '.' $PROLOGDOC/xml/pdng-pd2html.xsl doc/pdoc/$_.xml > doc/pdoc/$_.html");
}
exit 0;

sub run {
    my $cmd = shift;
    print STDERR "$cmd\n";
    if (system($cmd)) {
        print STDERR "Problem: $cmd\n";
        exit 1;
    }
}
